id: PF83CE998
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12514
  title: བཀའ་གདམས་གླེགས་བམ་ལས་བཏུས་པའི་ཆོས་སྐོར།
  volumes:
    c7c8eec0b81444198a59fd1cdf8517e9:
      image_group_id: I1KG12518
      title: ''
      base_file: v001.txt
  author: ''
